server: 
  port: 7032
  address: localhost
  session:
    timeout: 600
  contextPath: /rujianbin-app-websocket-chatroom

nio:
  jdk:
    socket-port: 7090
    socket-num: 5




    
    
    
    
    