server:
  port: 7042
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7040/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    appname: eureka-provider:${random.int(100)}
    lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: rujianbin-eureka-provider





    
    
    
    
    