server:
  port: 7041
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7040/eureka/
  instance:
    prefer-ip-address: true
    appname: xxccvv
spring:
  application:
    name: rujianbin-eureka-provider



    
    
    
    
    