encrypt:
  key: QAD
server:
  port: 7056
spring:
  application:
    name: rujianbin-eureka-configcenter-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rujianbin/spring-cloud-configcenter-file/    #路径到工程名
          search-paths: '{application}'        #git工程下的搜索路径，多个以逗号分隔,{application}表示用客户端的spring.application.name占位
          username: 769524791@qq.com
          password: 881030ru
          force-pull: true
          basedir: rujianbin-springcloud/${spring.application.name}/config-repo    #配置文件从git上clone后的缓存地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7040/eureka/   #将配置中心作为服务注册到eureka，实现高可用


