server: 
  port: 7010
  address: localhost
  session:
    timeout: 600
  contextPath: /rujianbin-oauth2
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true


    
    
    
    
    