encrypt:
  key: QAD
server:
  port: 7056
spring:
  application:
    name: rujianbin-eureka-configcenter-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rujianbin/spring-cloud-configcenter-file/    #路径到工程名
          search-paths: '{application}'        #git工程下的搜索路径，多个以逗号分隔,{application}表示用客户端的spring.application.name占位
          username: '{cipher}de9d50bf0658d71d06159327e25fd581f3099c226a8fe67c7ae5a42a29919a43f9f2286215fae19dd69ef603e29c6081'  #git账号
          password: '{cipher}7aac20766405a84be5db7dc9ec8639ff13a54be3a6c94a7edce448e5ea39f118'   #git密码
          basedir: D:\devDirectory\workspace\sp_idea_demo\rujianbin-springcloud\rujianbin-eureka-configcenter-server\config-repo     #配置文件从git上clone后的缓存地址

