server:
  port: 7041
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7040/eureka/
  instance:
    prefer-ip-address: true
    appname: sid1-eureka-provider
spring:
  application:
    name: rujianbin-eureka-provider1



    
    
    
    
    