server: 
  port: 7046
eureka:
  client:
      service-url:
        defaultZone: http://localhost:7040/eureka/
      fetch-registry: true
      registry-fetch-interval-seconds: 10
  instance:
      prefer-ip-address: true
      appname: eureka-consumer
spring:
  application:
    name: rujianbin-eureka-consumer

logging:
  level:
    rujianbin:
      eureka:
        consumer:
          service: INFO
rujianbin:
  testName: local-safwer2


    
    
    
    
    