spring:
  freemarker:
    variables:
      static: http://127.0.0.1/static/
      jsVersion: 1.0.0
      baseContext: rujianbin-app-web
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/template/freemarker/
    settings:
      template_update_delay: 1